"""
Tests for the idempotent-write behavior added to docs.py (Fix A).

Goal: `loom sync` writing equal content (modulo the auto-generated
timestamp header) should NOT modify the file's mtime, so a no-op
regeneration produces no `git status` diff.

Covers:
  * _normalize_for_compare strips the timestamp line
  * _write_doc_if_changed writes on first call, skips on identical,
    writes when content changes
  * generate_requirements_doc + generate_test_spec_doc preserve mtime
    when re-run with no semantic change
"""
from __future__ import annotations

import time
from datetime import datetime, timezone
from pathlib import Path

import pytest

from loom.docs import (
    _normalize_for_compare,
    _write_doc_if_changed,
    generate_requirements_doc,
    generate_test_spec_doc,
)
from loom.store import LoomStore, Requirement


@pytest.fixture
def store(tmp_path):
    return LoomStore("test-docs-idem", data_dir=tmp_path / "loom-data")


@pytest.fixture
def sample_embedding():
    return [0.1] * 768


class TestNormalizeForCompare:
    def test_strips_canonical_timestamp(self):
        a = (
            "# Doc\n\n*Auto-generated by Loom — 2026-05-22 12:34 UTC*\n\nbody\n"
        )
        b = (
            "# Doc\n\n*Auto-generated by Loom — 2026-05-23 09:01 UTC*\n\nbody\n"
        )
        assert _normalize_for_compare(a) == _normalize_for_compare(b)

    def test_preserves_body_diffs(self):
        a = "*Auto-generated by Loom — 2026-05-22 12:34 UTC*\nbody one"
        b = "*Auto-generated by Loom — 2026-05-22 12:34 UTC*\nbody two"
        assert _normalize_for_compare(a) != _normalize_for_compare(b)

    def test_no_timestamp_passes_through(self):
        # Content without the timestamp header isn't mangled.
        c = "# Doc\n\nbody"
        assert _normalize_for_compare(c) == c

    def test_multiple_timestamp_lines_all_stripped(self):
        # Defensive: if a doc grew a second timestamp (unlikely but
        # cheap to cover), both should be stripped.
        c = (
            "*Auto-generated by Loom — 2026-01-01 00:00 UTC*\n"
            "body\n"
            "*Auto-generated by Loom — 2026-02-01 00:00 UTC*\n"
        )
        normalized = _normalize_for_compare(c)
        assert "Auto-generated" not in normalized


class TestWriteDocIfChanged:
    def test_writes_on_first_call(self, tmp_path):
        target = tmp_path / "x.md"
        wrote = _write_doc_if_changed(target, "hello\n")
        assert wrote is True
        assert target.read_text(encoding="utf-8") == "hello\n"

    def test_skips_on_byte_equal(self, tmp_path):
        target = tmp_path / "x.md"
        target.write_text("hello\n", encoding="utf-8")
        first_mtime = target.stat().st_mtime
        time.sleep(0.05)  # ensure mtime resolution would change if written
        wrote = _write_doc_if_changed(target, "hello\n")
        assert wrote is False
        assert target.stat().st_mtime == first_mtime

    def test_skips_when_only_timestamp_differs(self, tmp_path):
        target = tmp_path / "x.md"
        old = (
            "# Doc\n\n*Auto-generated by Loom — 2026-05-22 12:34 UTC*\n\nbody\n"
        )
        new = (
            "# Doc\n\n*Auto-generated by Loom — 2026-05-23 09:01 UTC*\n\nbody\n"
        )
        target.write_text(old, encoding="utf-8")
        first_mtime = target.stat().st_mtime
        time.sleep(0.05)
        wrote = _write_doc_if_changed(target, new)
        assert wrote is False
        assert target.stat().st_mtime == first_mtime
        # Old content preserved on disk (including old timestamp).
        assert target.read_text(encoding="utf-8") == old

    def test_writes_when_body_changes(self, tmp_path):
        target = tmp_path / "x.md"
        target.write_text("body one\n", encoding="utf-8")
        wrote = _write_doc_if_changed(target, "body two\n")
        assert wrote is True
        assert target.read_text(encoding="utf-8") == "body two\n"


class TestGeneratorsIdempotent:
    """End-to-end: re-running the generator on an unchanged store
    should NOT change the file's mtime."""

    def _seed_one_req(self, store, embedding):
        req = Requirement(
            id="REQ-x",
            domain="behavior",
            value="example requirement",
            source_msg_id="msg-1",
            source_session="test",
            timestamp=datetime.now(timezone.utc).isoformat(),
            rationale="because",
        )
        store.add_requirement(req, embedding)

    def test_requirements_doc_idempotent_on_no_change(
        self, store, sample_embedding, tmp_path,
    ):
        self._seed_one_req(store, sample_embedding)
        out_dir = tmp_path / "docs"
        out_dir.mkdir()

        path = generate_requirements_doc(store, out_dir)
        first_mtime = path.stat().st_mtime

        time.sleep(0.05)  # let mtime resolution tick
        path2 = generate_requirements_doc(store, out_dir)
        assert path == path2
        assert path.stat().st_mtime == first_mtime, (
            "REQUIREMENTS.md mtime changed despite no store-level change"
        )

    def test_test_spec_doc_idempotent_on_no_change(
        self, store, sample_embedding, tmp_path,
    ):
        self._seed_one_req(store, sample_embedding)
        out_dir = tmp_path / "docs"
        out_dir.mkdir()

        path = generate_test_spec_doc(store, out_dir, specs={})
        first_mtime = path.stat().st_mtime

        time.sleep(0.05)
        path2 = generate_test_spec_doc(store, out_dir, specs={})
        assert path == path2
        assert path.stat().st_mtime == first_mtime, (
            "TEST_SPEC.md mtime changed despite no store-level change"
        )

    def test_requirements_doc_writes_when_store_changes(
        self, store, sample_embedding, tmp_path,
    ):
        self._seed_one_req(store, sample_embedding)
        out_dir = tmp_path / "docs"
        out_dir.mkdir()

        path = generate_requirements_doc(store, out_dir)
        first_mtime = path.stat().st_mtime

        # Add a second req → real semantic change → mtime should advance.
        req2 = Requirement(
            id="REQ-y",
            domain="behavior",
            value="second requirement",
            source_msg_id="msg-2",
            source_session="test",
            timestamp=datetime.now(timezone.utc).isoformat(),
            rationale="because",
        )
        store.add_requirement(req2, sample_embedding)

        time.sleep(0.05)
        generate_requirements_doc(store, out_dir)
        assert path.stat().st_mtime != first_mtime
