"""
Loom Document Generator - Maintains REQUIREMENTS.md and TEST_SPEC.md
"""

import re
from pathlib import Path
from datetime import datetime, timezone
from typing import List, Dict, Optional, Tuple, Set

from .store import LoomStore, Requirement
from .testspec import TestSpec, TestSpecStore


# M-fix-A — strip the auto-generated timestamp line before comparing
# old vs new content. Same input → same bytes modulo this line, so a
# regeneration that only changes the timestamp should be a no-op
# write (preserves mtime, keeps `git status` clean).
_TIMESTAMP_LINE_RE = re.compile(
    r"^\*Auto-generated by Loom.*?\*$",
    re.MULTILINE,
)


def _normalize_for_compare(content: str) -> str:
    """Return content with the auto-generated timestamp line removed
    so byte-equal content (modulo regeneration time) compares equal."""
    return _TIMESTAMP_LINE_RE.sub("", content)


def _write_doc_if_changed(path: Path, content: str) -> bool:
    """Write ``content`` to ``path`` only if the content (minus the
    auto-generated timestamp line) differs from what's already on
    disk. Returns True when a write happened, False when skipped.

    Skipping the write preserves the file's mtime, which is what
    keeps ``git status`` clean after a no-op regeneration.
    """
    if path.exists():
        try:
            existing = path.read_text(encoding="utf-8")
        except OSError:
            existing = None
        if existing is not None and (
            _normalize_for_compare(existing) == _normalize_for_compare(content)
        ):
            return False
    path.write_text(content, encoding="utf-8")
    return True


def _format_spec_block(store: LoomStore, req_id: str, superseded_req_ids: Set[str]) -> List[str]:
    """Format the Specifications section under a requirement, with each spec's implementations."""
    specs = store.get_specifications_for_requirement(req_id)
    active_specs = [s for s in specs if not s.superseded_at]

    lines = []
    if active_specs:
        lines.append(f"- **Specifications ({len(active_specs)}):**")
        for spec in active_specs:
            lines.append(f"  - `{spec.id}` [{spec.status}] {spec.description[:80]}")
            spec_impls = store.get_implementations_for_specification(spec.id)
            if spec_impls:
                for impl in spec_impls:
                    lines.append(f"    - `{impl.file}` (lines {impl.lines})")
            else:
                lines.append(f"    - *No implementation linked*")
    else:
        lines.append("- **Specifications:** *None yet*")

    # Show direct (non-spec) implementation links as a fallback/legacy section
    direct_impls = [
        i for i in store.get_implementations_for_requirement(req_id)
        if not (i.satisfies_specs or [])
    ]
    if direct_impls:
        lines.append("- **Direct implementation links (consider adding specs):**")
        for impl in direct_impls:
            loc = f"`{impl.file}` (lines {impl.lines})"
            drifted = any(
                s["req_id"] in superseded_req_ids
                for s in impl.satisfies
                if s["req_id"] == req_id
            )
            if drifted:
                lines.append(f"  - {loc} — **drift detected**")
            else:
                lines.append(f"  - {loc}")

    return lines


def _format_impl_links(store: LoomStore, req_id: str, superseded_req_ids: Set[str]) -> List[str]:
    """Legacy flat format (kept for tests). Prefer _format_spec_block."""
    impls = store.get_implementations_for_requirement(req_id)
    if not impls:
        return ["- **Implementations:** *None yet*"]

    lines = ["- **Implementations:**"]
    for impl in impls:
        loc = f"`{impl.file}` (lines {impl.lines})"
        drifted = any(
            s["req_id"] in superseded_req_ids
            for s in impl.satisfies
            if s["req_id"] == req_id
        )
        if drifted:
            lines.append(f"  - {loc} — **drift detected**")
        else:
            lines.append(f"  - {loc}")
    return lines


def _format_link_chain(store: LoomStore, link_ids: List[str], *, value_chars: int = 80, rationale_chars: int = 80) -> List[str]:
    """Render a "Builds on:" entry per linked req (M11.2).

    Each line shows ``REQ-id`` plus the parent's value (truncated)
    plus the parent's rationale (truncated, italicized) when present.
    Returns a list of markdown lines (no leading/trailing blanks).
    """
    if not link_ids:
        return []
    out: List[str] = []
    for lid in link_ids:
        parent = store.get_requirement(lid)
        if parent is None:
            out.append(f"- `{lid}` *(missing — was the link target deleted?)*")
            continue
        value = parent.value
        if len(value) > value_chars:
            value = value[:value_chars - 1].rstrip() + "…"
        line = f"- `{parent.id}` — {value}"
        if parent.rationale:
            r = parent.rationale
            if len(r) > rationale_chars:
                r = r[:rationale_chars - 1].rstrip() + "…"
            line += f"\n  *Rationale: {r}*"
        out.append(line)
    return out


# M12.2 — per-kind doc config. Each kind gets its own output file
# with kind-appropriate title, intro, and noun. Kinds NOT in this
# map (currently all are present) fall back to the requirement
# defaults.
KIND_DOC_CONFIG = {
    "requirement": {
        "filename": "REQUIREMENTS.md",
        "title": "Requirements Document",
        "noun": "Requirement",          # singular for body text
        "noun_plural": "Requirements",  # plural for headers
        "intro_extra": None,
    },
    "finding": {
        "filename": "FINDINGS.md",
        "title": "Findings",
        "noun": "Finding",
        "noun_plural": "Findings",
        "intro_extra": (
            "Empirical observations from this project. Each finding is "
            "grounded in experimental work referenced via its rationale "
            "and linked code (harness scripts, summary data)."
        ),
    },
    "methodology": {
        "filename": "METHODOLOGY.md",
        "title": "Methodology Decisions",
        "noun": "Methodology decision",
        "noun_plural": "Methodology decisions",
        "intro_extra": (
            "Procedural decisions that govern how research and "
            "development proceeds in this project. These are not "
            "imperative product requirements; they shape future "
            "experimental design."
        ),
    },
    "hypothesis": {
        "filename": "HYPOTHESES.md",
        "title": "Hypotheses",
        "noun": "Hypothesis",
        "noun_plural": "Hypotheses",
        "intro_extra": (
            "Pre-experiment claims awaiting test, plus past hypotheses "
            "with their confirmation/falsification outcome (linked to "
            "findings)."
        ),
    },
    "process_rule": {
        "filename": "PROCESS-RULES.md",
        "title": "Process Rules",
        "noun": "Process rule",
        "noun_plural": "Process rules",
        "intro_extra": (
            "Workflow rules — capture/retention/release discipline. "
            "These govern how the team operates, not what the system does."
        ),
    },
}


def generate_requirements_doc(
    store: LoomStore, output_dir: Path,
    private_ids: Set[str] = None, public_mode: bool = False,
    kind: str = "requirement",
) -> Path:
    """Generate a per-kind doc (M12.2). Default kind=requirement
    produces REQUIREMENTS.md (the legacy behavior). Other kinds
    produce kind-appropriate files (FINDINGS.md, METHODOLOGY.md,
    HYPOTHESES.md, PROCESS-RULES.md) with kind-aware intro text.

    Args:
        store: LoomStore instance
        output_dir: Where to write the file
        private_ids: Set of requirement IDs to exclude (if public_mode)
        public_mode: If True, exclude private requirements
        kind: M12.1 kind filter. Output is restricted to reqs with
              this kind; filename and title are kind-appropriate.

    Note: kind="requirement" is the default to preserve existing
    behavior for callers that don't yet pass kind explicitly. The
    output_dir will receive REQUIREMENTS.md as before. New kinds
    get their own files via this same entry point.
    """
    cfg = KIND_DOC_CONFIG.get(kind, KIND_DOC_CONFIG["requirement"])
    private_ids = private_ids or set()
    all_reqs = store.list_requirements(include_superseded=False)
    # M12.7b: filter archived items. store.list_requirements only
    # filters by superseded_at; archived is a status value and leaks
    # through. The doc generator must surface neither — archived items
    # would otherwise show up as "Active <kind>: N+1" with the archived
    # one rendered as if active.
    # M14.3: also hide "provisional" — intake-captured items waiting
    # for the user to promote them via `loom set-status`. They live
    # in the store (visible to `loom triage` / `loom doctor`) but
    # don't pollute the published REQUIREMENTS.md.
    reqs = [
        r for r in all_reqs
        if r.kind == kind and r.status not in ("archived", "provisional")
    ]
    superseded_all = [
        r for r in store.list_requirements(include_superseded=True)
        if r.superseded_at
    ]
    superseded = [r for r in superseded_all if r.kind == kind]
    superseded_ids = {r.id for r in superseded_all}  # not just our kind — for spec-block dimming

    if public_mode:
        reqs = [r for r in reqs if r.id not in private_ids]
        superseded = [r for r in superseded if r.id not in private_ids]

    # Group by domain
    by_domain: Dict[str, List[Requirement]] = {}
    for req in reqs:
        by_domain.setdefault(req.domain, []).append(req)

    # Pre-fetch all implementation + spec data for the traceability matrix
    req_impls: Dict[str, list] = {}
    req_specs: Dict[str, list] = {}
    for req in reqs:
        req_impls[req.id] = store.get_implementations_for_requirement(req.id)
        req_specs[req.id] = [s for s in store.get_specifications_for_requirement(req.id) if not s.superseded_at]

    lines = [
        f"# {cfg['title']}",
        "",
        f"*Auto-generated by Loom — {datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M UTC')}*",
        "",
    ]
    if cfg["intro_extra"]:
        lines.append(cfg["intro_extra"])
        lines.append("")
    lines.extend([
        f"**Active {cfg['noun_plural']}:** {len(reqs)}  ",
        f"**Superseded:** {len(superseded)}",
        "",
        "---",
        "",
    ])

    # Domain order
    domain_order = ["terminology", "behavior", "ui", "data", "architecture"]
    domains = sorted(by_domain.keys(), key=lambda d: domain_order.index(d) if d in domain_order else 99)

    for domain in domains:
        domain_reqs = by_domain[domain]
        lines.append(f"## {domain.title()}")
        lines.append("")
        for req in sorted(domain_reqs, key=lambda r: r.timestamp):
            # M11.2: surface rationale_needed as a visible marker on
            # the heading so debt is impossible to overlook in scans.
            if req.status == "rationale_needed":
                lines.append(f"### {req.id}   ⚠ rationale_needed")
            else:
                lines.append(f"### {req.id}")
            lines.append("")
            lines.append(f"> {req.value}")
            lines.append("")
            lines.append(f"- **Source:** {req.source_session}")
            lines.append(f"- **Added:** {req.timestamp[:10]}")
            lines.append(f"- **Status:** {req.status}")
            if getattr(req, 'rationale', None):
                lines.append(f"- **Rationale:** {req.rationale}")
            # M11.2: structured citation chain.
            link_ids = getattr(req, 'rationale_links', None) or []
            if link_ids:
                lines.append("")
                lines.append("**Builds on:**")
                lines.append("")
                lines.extend(_format_link_chain(store, link_ids))
                lines.append("")
            # M11.2: remediation prompt for visible-debt reqs.
            if req.status == "rationale_needed" and not req.rationale and not link_ids:
                lines.append("")
                lines.append(
                    "**Rationale needed.** No prose rationale captured and no "
                    "linkage to prior decisions found. Resolve by running "
                    f"`loom extract --rationale \"...\"` or `loom extract "
                    f"--derives-from REQ-X` again, then `loom set-status "
                    f"{req.id} pending`."
                )
                lines.append("")
            lines.extend(_format_spec_block(store, req.id, superseded_ids))
            lines.append("")
        lines.append("---")
        lines.append("")

    # Superseded section
    if superseded:
        lines.append(f"## Superseded {cfg['noun_plural']}")
        lines.append("")
        lines.append(
            f"*These {cfg['noun_plural'].lower()} have been replaced by "
            f"newer versions.*"
        )
        lines.append("")
        for req in superseded:
            lines.append(f"- ~~{req.id}: {req.value}~~ (superseded {req.superseded_at[:10]})")
        lines.append("")

    # M12.2: traceability matrix only makes sense for kind=requirement
    # — findings/methodology/etc don't have specs/impls in the
    # implementation sense.
    if kind != "requirement":
        output_path = output_dir / cfg["filename"]
        _write_doc_if_changed(output_path, "\n".join(lines))
        return output_path

    # Traceability matrix — three layers
    lines.append("## Traceability Matrix")
    lines.append("")
    lines.append("*Requirements → Specifications → Implementations*")
    lines.append("")

    # M11.2: include "Derives from" column only when at least one
    # active req has linkage. Avoids cluttering the matrix for
    # projects that haven't started using rationale_links yet.
    any_links = any(
        getattr(r, 'rationale_links', None) for r in reqs
    )
    if any_links:
        lines.append("| Requirement | Domain | Derives from | Specs | Files | Test Spec |")
        lines.append("|---|---|---|---|---|---|")
    else:
        lines.append("| Requirement | Domain | Specs | Files | Test Spec |")
        lines.append("|---|---|---|---|---|")
    for req in sorted(reqs, key=lambda r: r.domain + r.timestamp):
        specs = req_specs.get(req.id, [])
        impls = req_impls.get(req.id, [])

        if specs:
            specs_str = ", ".join(f"`{s.id}`" for s in specs)
        else:
            specs_str = "—"

        if impls:
            files = ", ".join(f"`{impl.file}`" for impl in impls)
        else:
            files = "—"

        test = req.test_spec_id if req.test_spec_id else "—"

        if any_links:
            link_ids = getattr(req, 'rationale_links', None) or []
            derives = ", ".join(f"`{lid}`" for lid in link_ids) if link_ids else "—"
            lines.append(
                f"| {req.id} | {req.domain} | {derives} | "
                f"{specs_str} | {files} | {test} |"
            )
        else:
            lines.append(
                f"| {req.id} | {req.domain} | {specs_str} | {files} | {test} |"
            )
    lines.append("")

    output_path = output_dir / cfg["filename"]
    _write_doc_if_changed(output_path, "\n".join(lines))
    return output_path


def generate_test_spec_doc(store: LoomStore, output_dir: Path, specs: Dict[str, TestSpec] = None, private_ids: Set[str] = None, public_mode: bool = False) -> Path:
    """Generate TEST_SPEC.md from requirements and test specifications.
    
    Args:
        store: LoomStore instance
        output_dir: Where to write the file
        specs: Dict of req_id -> TestSpec
        private_ids: Set of requirement IDs to exclude (if public_mode)
        public_mode: If True, exclude private requirements
    """
    private_ids = private_ids or set()
    reqs = store.list_requirements(include_superseded=False)
    # M12.7b: same archived-leak fix as generate_requirements_doc.
    # M14.3: also hide provisional captures (awaiting promotion).
    reqs = [r for r in reqs if r.status not in ("archived", "provisional")]
    specs = specs or {}

    if public_mode:
        reqs = [r for r in reqs if r.id not in private_ids]
    
    lines = [
        "# Test Specification",
        "",
        f"*Auto-generated by Loom — {datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M UTC')}*",
        "",
        "This document describes how to verify each requirement.",
        "",
        "| Status | Meaning |",
        "|--------|---------|",
        "| ✅ | Has test specification |",
        "| ⚠️ | Needs test specification |",
        "| 🔄 | Requirement changed, test needs review |",
        "",
        "---",
        "",
    ]
    
    # Group by domain
    by_domain: Dict[str, List[Requirement]] = {}
    for req in reqs:
        by_domain.setdefault(req.domain, []).append(req)
    
    domain_order = ["terminology", "behavior", "ui", "data", "architecture"]
    domains = sorted(by_domain.keys(), key=lambda d: domain_order.index(d) if d in domain_order else 99)
    
    needs_spec = 0
    has_spec = 0
    
    for domain in domains:
        domain_reqs = by_domain[domain]
        lines.append(f"## {domain.title()}")
        lines.append("")
        
        for req in sorted(domain_reqs, key=lambda r: r.timestamp):
            spec = specs.get(req.id)
            impls = store.get_implementations_for_requirement(req.id)

            if spec:
                has_spec += 1
                status = "✅"
                lines.append(f"### {status} {req.id}")
                lines.append("")
                lines.append(f"**Requirement:** {req.value}")
                lines.append("")
                lines.append(f"**Test:** {spec.description}")
                lines.append("")
                if spec.steps:
                    lines.append("**Steps:**")
                    for i, step in enumerate(spec.steps, 1):
                        lines.append(f"{i}. {step}")
                    lines.append("")
                lines.append(f"**Expected:** {spec.expected}")
                lines.append("")
                if impls:
                    lines.append("**Covered code:**")
                    for impl in impls:
                        lines.append(f"- `{impl.file}` (lines {impl.lines})")
                    lines.append("")
                if spec.automated:
                    lines.append("*Automated: Yes*")
                if spec.last_verified:
                    lines.append(f"*Last verified: {spec.last_verified}*")
                lines.append("")
            else:
                needs_spec += 1
                status = "⚠️"
                lines.append(f"### {status} {req.id}")
                lines.append("")
                lines.append(f"**Requirement:** {req.value}")
                lines.append("")
                lines.append("**Test:** *Needs specification*")
                lines.append("")
                if impls:
                    lines.append("**Uncovered code:**")
                    for impl in impls:
                        lines.append(f"- `{impl.file}` (lines {impl.lines})")
                    lines.append("")
                lines.append("```")
                lines.append("TODO: Define test steps and expected outcome")
                lines.append("```")
                lines.append("")
        
        lines.append("---")
        lines.append("")
    
    # Summary
    lines.insert(8, f"**Coverage:** {has_spec}/{has_spec + needs_spec} requirements have test specs")
    lines.insert(9, "")
    
    output_path = output_dir / "TEST_SPEC.md"
    _write_doc_if_changed(output_path, "\n".join(lines))
    return output_path


def check_conflicts(store: LoomStore, new_req: Requirement, get_embedding_fn=None, threshold: float = 0.85) -> List[Dict]:
    """
    Check if a new requirement conflicts with existing ones.
    
    Uses semantic similarity to find potential conflicts.
    Returns list of potential conflicts with similarity scores.
    """
    conflicts = []
    
    existing = store.list_requirements(include_superseded=False)
    
    # If we have embedding function, use semantic search
    if get_embedding_fn:
        new_embedding = get_embedding_fn(new_req.value)
        similar = store.search_requirements(new_embedding, n=5)
        
        for match in similar:
            req = match["requirement"]
            distance = match.get("distance", 1.0)
            
            # ChromaDB returns L2 distance, lower = more similar
            # Convert to similarity (rough approximation)
            similarity = max(0, 1 - (distance / 2))
            
            if req.id != new_req.id and similarity > threshold:
                # High similarity in same domain = likely conflict
                if req.domain == new_req.domain:
                    conflicts.append({
                        "existing": req,
                        "similarity": similarity,
                        "reason": f"High semantic similarity ({similarity:.0%}) in same domain"
                    })
                elif similarity > 0.9:
                    # Very high similarity across domains
                    conflicts.append({
                        "existing": req,
                        "similarity": similarity,
                        "reason": f"Very high semantic similarity ({similarity:.0%})"
                    })
    
    # Also check for keyword-based conflicts
    for req in existing:
        if req.id == new_req.id:
            continue
        if any(c["existing"].id == req.id for c in conflicts):
            continue  # Already found via semantic search
            
        # Same domain with significant word overlap
        if req.domain == new_req.domain:
            new_lower = new_req.value.lower()
            old_lower = req.value.lower()
            
            new_words = set(new_lower.split())
            old_words = set(old_lower.split())
            overlap = new_words & old_words
            
            # Exclude common words
            stopwords = {"the", "a", "an", "is", "are", "should", "be", "to", "for", "with", "and", "or"}
            meaningful_overlap = overlap - stopwords
            
            if len(meaningful_overlap) >= 3:
                conflicts.append({
                    "existing": req,
                    "overlap": meaningful_overlap,
                    "reason": f"Overlapping terms: {', '.join(list(meaningful_overlap)[:5])}"
                })
    
    return conflicts


def analyze_test_impact(store: LoomStore, changed_req: Requirement, specs: Dict[str, TestSpec]) -> List[str]:
    """
    Analyze which tests are impacted by a requirement change.
    
    Returns list of affected test IDs.
    """
    affected = []
    
    # Direct impact - test for this requirement
    if changed_req.id in specs:
        affected.append(changed_req.id)
    
    # Indirect impact - tests that depend on related requirements
    # (This would use the implementation links to find related code/tests)
    
    return affected
