"""
Test-runner registry for ``loom_exec``.

Each entry describes how to grade a task for a particular language/test
framework:

    language     "python" | "dart" | "typescript"
    file_ext     canonical source extension for the target (informational)
    test_ext     file suffix for tests (".py", ".dart", ".test.ts")
    apply_mode   "append" — append model output to files_to_modify[0]
                     (works for Python: last-definition wins)
                 "replace" — overwrite files_to_modify[0] with the model's
                     full file content (required for Dart/TS/any language
                     that can't redefine a class or export)
    fence        Markdown fenced-code language tag for the prompt
    build_command(test_target, cwd) -> list[str]
                 Shell command to run for grading. test_target is the
                 Loom "path::name" form; runners that don't use that
                 form split on "::" and pass the name via their own
                 filter flag.
    parse(stdout, stderr, returncode) -> (passed, total, tail)
                 How many passed, total collected, last ~14 lines of
                 output for diagnostics.
    skeleton(class_or_group) -> str
                 Contents of the failing-placeholder test skeleton
                 ``loom spec --test`` writes when this runner is active.

The module is data-only — no Loom-store or CLI coupling. Keeps it
unit-testable in isolation and lets ``loom_exec`` stay a thin dispatcher.
"""
from __future__ import annotations

import re
import sys
from pathlib import Path
from typing import Callable, NamedTuple

# ANSI escape codes appear in vitest output. Strip before parsing.
ANSI_RE = re.compile(r"\x1b\[[0-9;]*[A-Za-z]")


def _strip_ansi(s: str) -> str:
    return ANSI_RE.sub("", s)


class Runner(NamedTuple):
    name: str
    language: str
    file_ext: str
    test_ext: str
    apply_mode: str  # "append" | "replace"
    fence: str
    build_command: Callable[[str, Path], list[str]]
    parse: Callable[[str, str, int], tuple[int, int, str]]
    skeleton: Callable[[str], str]


# ---------------------------------------------------------------------------
# pytest — the default, matches the behavior loom_exec shipped with.
# ---------------------------------------------------------------------------

def _pytest_command(test_target: str, cwd: Path) -> list[str]:
    return [sys.executable, "-m", "pytest", test_target, "-v", "--tb=line"]


def _pytest_parse(stdout: str, stderr: str, rc: int) -> tuple[int, int, str]:
    combined = (stdout or "") + "\n" + (stderr or "")
    passed = combined.count(" PASSED")
    failed = combined.count(" FAILED")
    errored = combined.count(" ERROR")
    total = passed + failed + errored
    tail = "\n".join(combined.splitlines()[-14:])
    return passed, total, tail


def _pytest_skeleton(class_name: str) -> str:
    return (
        '"""Grading test — auto-generated by Loom.\n\n'
        'Replace the placeholder with real behavior assertions BEFORE\n'
        'running loom_exec. The placeholder fails on purpose so an empty\n'
        'skeleton can\'t be mistaken for a pass.\n'
        '"""\n'
        'import pytest\n\n\n'
        f'class {class_name}:\n'
        '    def test_placeholder_replace_me(self):\n'
        '        pytest.fail(\n'
        '            "Replace with real assertions before running loom_exec"\n'
        '        )\n'
    )


# ---------------------------------------------------------------------------
# flutter_test — delegates to `dart test` under the hood (Flutter test uses
# the same reporter). We key on test_target = "path::GroupName" and pass
# the group via --plain-name for exact-match filtering.
# ---------------------------------------------------------------------------

# Matches the Dart test reporter summary line.
# Pass-only:   "00:01 +3: All tests passed!"
# Mixed:       "00:01 +2 -1: Some tests failed."
_DART_SUMMARY_RE = re.compile(
    r"\+(\d+)(?:\s+~\d+)?(?:\s+-(\d+))?(?:\s*:\s*(.*))?",
)


def _split_target(test_target: str) -> tuple[str, str]:
    if "::" in test_target:
        path, _, name = test_target.partition("::")
        return path, name
    return test_target, ""


def _flutter_command(test_target: str, cwd: Path) -> list[str]:
    path, name = _split_target(test_target)
    cmd = ["flutter", "test", path, "--reporter", "expanded"]
    if name:
        cmd += ["--plain-name", name]
    return cmd


def _dart_command(test_target: str, cwd: Path) -> list[str]:
    """Pure-Dart test runner (for non-Flutter Dart packages)."""
    path, name = _split_target(test_target)
    cmd = ["dart", "test", path]
    if name:
        cmd += ["--plain-name", name]
    return cmd


def _dart_parse(stdout: str, stderr: str, rc: int) -> tuple[int, int, str]:
    combined = _strip_ansi((stdout or "") + "\n" + (stderr or ""))
    # Scan lines; the LAST summary line is authoritative. Avoid matching
    # intermediate progress lines by picking the highest-count match.
    passed = 0
    failed = 0
    for m in _DART_SUMMARY_RE.finditer(combined):
        p = int(m.group(1) or 0)
        f = int(m.group(2) or 0)
        if (p + f) >= (passed + failed):
            passed, failed = p, f
    total = passed + failed
    # If the reporter never emitted a summary (compilation error, etc.),
    # fall back to returncode: 0 = passed_total_unknown, nonzero = failed.
    if total == 0 and rc != 0:
        failed = 1
        total = 1
    tail = "\n".join(combined.splitlines()[-14:])
    return passed, total, tail


def _dart_skeleton(group_name: str) -> str:
    return (
        '// Grading test — auto-generated by Loom.\n'
        '//\n'
        '// Replace the placeholder with real behavior assertions BEFORE\n'
        '// running loom_exec. The placeholder fails on purpose so an empty\n'
        '// skeleton can\'t be mistaken for a pass.\n'
        "import 'package:test/test.dart';\n\n"
        'void main() {\n'
        f"  group('{group_name}', () {{\n"
        "    test('placeholder — replace me', () {\n"
        "      fail('Replace with real assertions before running loom_exec');\n"
        '    });\n'
        '  });\n'
        '}\n'
    )


# ---------------------------------------------------------------------------
# vitest — npm-based TypeScript/JS test runner. Pass the filter via -t.
# ---------------------------------------------------------------------------

_VITEST_SUMMARY_RE = re.compile(
    r"Tests\s+(?:(\d+)\s+failed\s*\|\s*)?(?:(\d+)\s+passed\s*)?(?:\|\s*(\d+)\s+skipped\s*)?(?:\(\s*(\d+)\s*\))?",
)


def _vitest_command(test_target: str, cwd: Path) -> list[str]:
    path, name = _split_target(test_target)
    cmd = ["npx", "--no-install", "vitest", "run", path]
    if name:
        cmd += ["-t", name]
    return cmd


def _vitest_parse(stdout: str, stderr: str, rc: int) -> tuple[int, int, str]:
    combined = _strip_ansi((stdout or "") + "\n" + (stderr or ""))
    m = _VITEST_SUMMARY_RE.search(combined)
    passed = int(m.group(2)) if m and m.group(2) else 0
    failed = int(m.group(1)) if m and m.group(1) else 0
    total_paren = int(m.group(4)) if m and m.group(4) else None
    total = total_paren if total_paren is not None else (passed + failed)
    if total == 0 and rc != 0:
        # Collection / compile failure — count as one failed test so the
        # outcome classification sees a real failure rather than 0/0.
        failed = 1
        total = 1
    tail = "\n".join(combined.splitlines()[-14:])
    return passed, total, tail


def _vitest_skeleton(describe_name: str) -> str:
    return (
        '// Grading test — auto-generated by Loom.\n'
        '//\n'
        '// Replace the placeholder with real behavior assertions BEFORE\n'
        '// running loom_exec. The placeholder fails on purpose so an empty\n'
        '// skeleton can\'t be mistaken for a pass.\n'
        "import { describe, test, expect } from 'vitest';\n\n"
        f"describe('{describe_name}', () => {{\n"
        "  test('placeholder — replace me', () => {\n"
        "    expect.fail('Replace with real assertions before running loom_exec');\n"
        '  });\n'
        '});\n'
    )


# ---------------------------------------------------------------------------
# Registry
# ---------------------------------------------------------------------------

RUNNERS: dict[str, Runner] = {
    "pytest": Runner(
        name="pytest", language="python",
        file_ext=".py", test_ext=".py",
        apply_mode="append", fence="python",
        build_command=_pytest_command, parse=_pytest_parse,
        skeleton=_pytest_skeleton,
    ),
    "pytest_replace": Runner(
        name="pytest_replace", language="python",
        file_ext=".py", test_ext=".py",
        apply_mode="replace", fence="python",
        build_command=_pytest_command, parse=_pytest_parse,
        skeleton=_pytest_skeleton,
    ),
    "flutter_test": Runner(
        name="flutter_test", language="dart",
        file_ext=".dart", test_ext=".dart",
        apply_mode="replace", fence="dart",
        build_command=_flutter_command, parse=_dart_parse,
        skeleton=_dart_skeleton,
    ),
    "dart_test": Runner(
        name="dart_test", language="dart",
        file_ext=".dart", test_ext=".dart",
        apply_mode="replace", fence="dart",
        build_command=_dart_command, parse=_dart_parse,
        skeleton=_dart_skeleton,
    ),
    "vitest": Runner(
        name="vitest", language="typescript",
        file_ext=".ts", test_ext=".test.ts",
        apply_mode="replace", fence="typescript",
        build_command=_vitest_command, parse=_vitest_parse,
        skeleton=_vitest_skeleton,
    ),
}


def get_runner(name: str | None) -> Runner:
    """Return the Runner for ``name``. Defaults to pytest if unset or
    unknown — preserves legacy behavior and the `.loom-config.json` shipped
    before multi-runtime support existed."""
    if not name or name not in RUNNERS:
        return RUNNERS["pytest"]
    return RUNNERS[name]
